import = [
  "~/.config/alacritty/themes/themes/nightfox.toml"
]

[env]

TERM = "xterm-256color"

[window]

# decorations = "Transparent"
startup_mode = "Maximized"
padding.x = 10
padding.y = 0
opacity = 0.8
blur = true
option_as_alt = "Both"
dynamic_title=true

[font]

normal.family = "MesloLGS Nerd Font Mono"
size = 16

[scrolling]
history = 10000
