---

# ----------------------------------------------------
# Copy Config files over
# ----------------------------------------------------

- name: Setup various config files
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Copy Kitty Config
      ansible.builtin.copy:
        src: ../configs/kitty/
        dest: ~/.config/kitty/
        remote_src: yes

    - name: Copy Emacs
      ansible.builtin.copy:
        src: ../configs/emacs/
        dest: ~/.config/emacs/
        remote_src: yes
