---

# ----------------------------------------------------
# Copy Config files over
# ----------------------------------------------------

- name: Setup various config files
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Setup ZSHRC
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        block: "{{ item }}"
      with_items:
        - "{{lookup('ansible.builtin.file', '../configs/zshrc.sh') }}"
        
