---

# ----------------------------------------------------
# DOOM EMACS
# ----------------------------------------------------

- name: Clone Doom Emacs
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Clone Doom Emacs
      block:
        - name: Clone Doom Emacs repository
          git:
            repo: https://github.com/doomemacs/doomemacs
            dest: ~/.config/emacs
            depth:
          when: doom.enabled

        - name: Copy contents of configs/doom folder to ~/.config/doom/
          ansible.builtin.copy:
            src: ../configs/doom/
            dest: ~/.config/doom/
            remote_src: yes
          when: doom.enabled

        - name: Delete ~/.emacs.d folder
          ansible.builtin.file:
            path: ~/.emacs.d
            state: absent
          when: doom.enabled

        - name: Check if doom is installed
          shell: command -v doom >/dev/null 2>&1
          register: is_doom_installed
          ignore_errors: yes
          when: doom.enabled

        - name: Install Doom Emacs for the first time
          shell: ~/.config/emacs/bin/doom install
          when:
            - doom.enabled
            - is_doom_installed.rc != 0

        - name: Run doom sync
          shell: doom sync
          when: doom.enabled
