---

# ----------------------------------------------------
# EMACS
# ----------------------------------------------------

- name: Configure emacs
  hosts: localhost
  vars_files:
    - ../vars.yml
  tasks:
    - name: Delete ~/.emacs.d
      file:
        path: ~/.emacs.d
        state: absent

    - name: Copy Emacs
      ansible.builtin.copy:
        src: ../configs/emacs/
        dest: ~/.config/emacs/
        remote_src: yes
      when: not emacs.use_doom
        
    - name: Clone Doom Emacs repository
      git:
        repo: https://github.com/doomemacs/doomemacs
        dest: ~/.config/emacs
        depth: 1
        update: true
      when: emacs.use_doom

    - name: Copy contents of configs/doom folder to ~/.config/doom/
      ansible.builtin.copy:
        src: ../configs/doom/
        dest: ~/.config/doom/
        remote_src: yes
      when: emacs.use_doom

    - name: Delete ~/.emacs.d folder
      ansible.builtin.file:
        path: ~/.emacs.d
        state: absent
      when: emacs.use_doom

    - name: Check if doom is installed
      shell: command -v doom >/dev/null 2>&1
      register: is_doom_installed
      ignore_errors: yes
      when: emacs.use_doom
      changed_when: False

    - name: Install Doom Emacs for the first time
      shell: ~/.config/emacs/bin/doom install
      when:
        - emacs.use_doom
        - is_doom_installed.rc != 0

    - name: Run doom sync
      shell: doom sync
      when: emacs.use_doom
