---

# ----------------------------------------------------
# HOMEBREW
# ----------------------------------------------------

- name: Brew installations
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars.yml
  tasks:
    - name: Install Cask Apps
      community.general.homebrew_cask:
        name: '{{ item }}'
        state: latest
      loop: "{{ homebrew.cask }}"
      when: homebrew.enable_cask

    - name: Brew Taps
      community.general.homebrew_tap:
        name: '{{ item }}'
        state: present
      loop: "{{ homebrew.taps }}"

    - name: Install packages
      community.general.homebrew:
        name: '{{ item }}'
        state: upgraded
      loop: "{{ homebrew.packages }}"
