---

# ----------------------------------------------------
# HOMEBREW
# ----------------------------------------------------

- name: Brew installations
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install packages
      community.general.homebrew:
        name: '{{ item }}'
        state: latest
      loop:
        - nvm
        - terraform
        - pandoc
        - imagemagick
        - tmux
        - ripgrep
        - coreutils
        - emacs
        - fd
        - ffmpeg

# ----------------------------------------------------
# NVM/NODE/NPM/PNPM Setup
# ----------------------------------------------------

- name: NPM/PNPM Setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install latest node
      shell: source ~/.nvm/nvm.sh && nvm install node

    - name: Source ~/.nvm/nvm.sh
      shell: source ~/.nvm/nvm.sh && echo $PATH
      register: updated_path_output
      args:
        executable: /bin/bash

    - name: Set updated PATH as a fact
      set_fact:
        updated_path: "{{ updated_path_output.stdout }}"

    - name: Global installs via NPM
      community.general.npm:
        name: "{{ item }}"
        global: true
        state: latest
      loop:
        - pnpm
        - vercel
        - typescript
        - typescript-language-server
        - tide
        - prettier
      environment:
        PATH: "{{ updated_path }}"

# ----------------------------------------------------
# DOOM EMACS
# ----------------------------------------------------

- name: Clone Doom Emacs
  hosts: localhost
  tasks:
    - name: Clone Doom Emacs
      block:
        - name: Clone Doom Emacs repository
          git:
            repo: https://github.com/doomemacs/doomemacs
            dest: ~/.config/emacs
            depth: 1

        - name: Copy contents of backups/doom folder to ~/.config/doom/
          ansible.builtin.copy:
            src: backups/doom/
            dest: ~/.config/doom/
            remote_src: yes

        - name: Delete ~/.emacs.d folder
          ansible.builtin.file:
            path: ~/.emacs.d
            state: absent

        - name: Prompt - Doom Emacs installer
          ansible.builtin.debug:
            msg:
              - Doom Emacs is ready to install
              - If this is the first time, Run the following command '~/.config/emacs/bin/doom install'
              - Otherwise run '~/.config/emacs/bin/doom sync'
